### PR TITLE
Fix the build + make sure that future breakage does not go unnoticed

### PR DESCRIPTION
**Pull request by hartwork**
Hi!

This pull request:
- (Sits on top of #47 (for an actual chance on a green build) but I'm happy to rebase it off of it in case #47 gets merged first.)
- Fixes the build
- Adds essential CI so we'll notice if the build ever breaks again (see https://github.com/hartwork/cosinnus-devops/actions for the current build log)
- Configures GitHub Dependabot to keep the added GitHub Action up to date

What do you think?

Best, Sebastian

### CODE REVIEW

**Comment by hartwork** [comment]
What do you think?

**Comment by hartwork** [comment]
Closing after one month of no reply to keep my own listing at https://github.com/pulls clean

**Comment by saschasommer** [comment]
@hartwork Hi Sebastian. Sorry, I just came back from a longer vacation and haven't had the time to check back into the pulls until now. Could you please re-open the PR? We would very much like to merge it! Thank you for your work and sorry for the long delay!

**Comment by hartwork** [comment]
Hi @saschan, I have already deleted the fork and the branches but the _commits_ are still in here, so an easy way to merge them would be wget plus git-am. Let me do a precise demo of that idea:
```console
# git clone --depth 1 https://github.com/wechange-eg/cosinnus-devops
# cd cosinnus-devops
# git checkout -b fix-the-build
# wget https://github.com/wechange-eg/cosinnus-devops/commit/04051cd8cfa83902a543113284b983c12326d46f.patch
# wget https://github.com/wechange-eg/cosinnus-devops/commit/ed854c9647a06dde10772348979a93f27d7532a6.patch
# wget https://github.com/wechange-eg/cosinnus-devops/commit/42d1772f5b9281c134bda9d21631c1dbf1789861.patch
# wget https://github.com/wechange-eg/cosinnus-devops/commit/5eb6a39f4591a38db7500db925a5ffad761f8d59.patch
# git am *.patch
Applying: .gitmodules: Allow cloning of cosinnus-cloud without SSH access
Applying: Make GitHub Actions build using docker-compose
Applying: Use GitHub Dependabot to keep GitHub Actions up to date
Applying: Dockerfile: Use recent pip to fix the build of cryptography
# git checkout master
# git merge --no-ff --no-edit fix-the-build
# git --no-pager log --graph --oneline
*   6c656b6 (HEAD -> master) Merge branch 'fix-the-build'
|\  
| * 3cf5f95 (fix-the-build) Dockerfile: Use recent pip to fix the build of cryptography
| * 0a259ed Use GitHub Dependabot to keep GitHub Actions up to date
| * 18703a3 Make GitHub Actions build using docker-compose
| * b339698 .gitmodules: Allow cloning of cosinnus-cloud without SSH access
|/  
* 95600d1 (grafted, origin/master, origin/HEAD) Minor clarifications for readme.md
```
Does that approach work for you?

**Comment by saschasommer** [comment]
@hartwork worked perfectly. Thank you very much, we really appreciate your work on the fixes!

**Pull request closed without merging**
